### ISSUE TITLE
Baserow - Delete Row action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1642]
Implement the Delete Row action for the Baserow component to enable users to remove specific rows from a table within their Baserow database.

**Action properties:**
- table id - id of the table from which the row should be deleted
- row id - id of the row that needs to be deleted

**Ouput:**
- no output

Documentation Reference: https://baserow.io/api-docs

**Comment by arilloid** [comment]
Hello @monikakuster ,

I previously had to unassign myself from the related issue due to some personal circumstances, but I now have more time and resources to tackle adding new actions to the Baserow component. Could you please assign me to this issue? I’m ready to get started and see it through this time.

Thank you!
